### ISSUE TITLE
Loss of the pull argument

### ISSUE THREAD

**Issue by garthtarr** [mitchelloharawild/icon#20]
With the "old" icon package, there was the `pull` argument, do you know the easiest way to do this in the new package.

For example I used to have right aligned icons in my xaringan slide headings:

``` 
## Citations and references `r icon::fa("book", pull="right")`
```

If I try wrapping it in a standard `.right[]` it falls onto the next line:

``` 
## Citations and references .right[`r  icon::fontawesome("book")`]
```

Any ideas?

**Comment by mitchelloharawild** [comment]
Does this work for you?
````
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, Inc."
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# xaringan `r icon::icon_style(icon::fontawesome("rocket"), float = "right")`
````
